### ISSUE TITLE
很好地桌面应用

### ISSUE THREAD

**Issue by Evil0ctal** [Tairraos/TikDown#1]
请问可否将此仓库链接加入我的项目的自述文件中？

仓库地址：https://github.com/Evil0ctal/Douyin_TikTok_Download_API

**Comment by Tairraos** [comment]
拉到readme最下方，几天前就已经加入了你的仓库地址呀。感谢栏里的第一个地址就是它。

**Comment by Tairraos** [comment]
哦，可能我理解错了。
如果你是指把TikDown加入你的Repo里，当然可以。很高兴能得到你的link back.

**Comment by Tairraos** [comment]
没问题。我就是之前在你的Repo里向你提需求的人： https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/27

^_^

**Comment by Tairraos** [comment]
我还有一个100行代码的python版本。就是看了你的repo后第一时间写出来的，很小巧，舍不得删除。
但是python版本写UI比较麻烦，而且要打包成win/mac平台的app后会非常巨大，所以我最后选择了electron。

https://github.com/Tairraos/tiktok-downloader.py
