### ISSUE TITLE
I couldn't download the video

### ISSUE THREAD

**Issue by EdricSon** [Tairraos/TikDown#19]
I couldn't download the video

**Comment by Tairraos** [comment]
Is there some error? what's is your download link?

**Comment by EdricSon** [comment]
yesterday i still download normally , today i cant download

**Comment by Tairraos** [comment]
The parsing API is not working again, i will find how to fix it.

**Comment by EdricSon** [comment]
i still can't use to download tiktok videos

**Comment by Tairraos** [comment]
The downloader simulates as an ipad to accesss Tiktok API, and parses request URL to obtain the video CDN address. But tiktok detects the impersonation identifier and refuses to return  data, so the downloader doesn't work now. I am working on another download method to fix it, it will take some time.

**Comment by Tairraos** [comment]
tiktok download works now.

**Comment by EdricSon** [comment]
i still can't use to download douyin videos
