### ISSUE TITLE
Can you make a video download version from TikTok Global?

### ISSUE THREAD

**Issue by bpham1912** [Tairraos/TikDown#20]
**Can you make a video download version from TikTok Global?**

![image](https://user-images.githubusercontent.com/46698873/198874513-336775bc-a326-4392-84f0-1ef245c6108e.png)

**Comment by Tairraos** [comment]
This project is the downloader for tiktok. But it not work since tiktok upgraded API and i can't parse URL. I will find way to make it work again. Just waiting TikDown upgrage.
