### ISSUE TITLE
User data locations

### ISSUE THREAD

**Issue by viking1304** [Tairraos/TikDown#3]
I really like this application, so I made a [Homebrew](https://brew.sh/) formula yesterday, but I need to finish zap stanza in order to send a pull request to the official Homebrew repo.

Can you please tell me if there is any other place where the app stores data except in those two places:

~/Library/Application Support/Tiktok Downloader
~/Library/Preferences/com.tairraos.tikdown.plist

**Comment by Tairraos** [comment]
I stored  3 setting values depends on electron-settings 4.0.2 project. The project did compatible with mac/win/linux and so on. I only read document to figerout how to use, not sure the store place will limit on those 2 folders.

I think review source code to find answer is the best solution, but i am busy on another projcet yet. Sorry to say this: If you do got time to review source code of electron-settings, it will be fine. If do not, allow me delay few days to make answer.

**Comment by Tairraos** [comment]
Maybe we can do some talk if you allow. This is a wechat qrcode: 
![image](https://user-images.githubusercontent.com/185069/177159722-701fccc5-e50b-48c9-8871-6638de7a671b.png)
