### ISSUE TITLE
can you add douyin playlist's video bulk download feature?

### ISSUE THREAD

**Issue by Dragon-97** [Tairraos/TikDown#6]
can you add douyin playlist's video bulk download feature? . I want to select the first episode ID of that playlist. And from there automatically appear the videos of the next episodes downloaded along.
I hope you develop this feature further. 
Thank you very much

**Comment by Tairraos** [comment]
I only use tiktok/douyin on PC, don't know what is playlist. Is your mean the account info page? Could you provide a URL to help me get sense？

**Comment by Dragon-97** [comment]
https://www.douyin.com/video/7099786108078230816
here is an example this playlist has 31 episodes. I want to download all the above episodes in order from 1 to 31.
Or do you have a way to get the link of 31 episodes above quickly to help me. so i can use your app to download 31 episodes faster

**Comment by Tairraos** [comment]
The URL structure is same as a normal video URL, and how do you get it? Only can see different of normal video that is a episode list on right of video player.
This downloader is not spider machanism, only parsed API data will not parse page content(even never to get the dom content). So I can not know the URL appended a playlist behind a video.
The requirement is fit to implement with a new tool, like a tampermonkey script. Parse current page to get all play back url and auto fill in clipboard. TikDown watch(monitor) feature will auto get them and add them to download list.

**Comment by Dragon-97** [comment]
www.douyin.com/collection/7099812611583117345/1
www.douyin.com/collection/7099812611583117345/2
www.douyin.com/collection/7099812611583117345/3
www.douyin.com/collection/7099812611583117345/4
www.douyin.com/collection/7099812611583117345/5
www.douyin.com/collection/7099812611583117345/6
www.douyin.com/collection/7099812611583117345/7
www.douyin.com/collection/7099812611583117345/8
www.douyin.com/collection/7099812611583117345/9
www.douyin.com/collection/7099812611583117345/10
www.douyin.com/collection/7099812611583117345/11
www.douyin.com/collection/7099812611583117345/12
www.douyin.com/collection/7099812611583117345/13
www.douyin.com/collection/7099812611583117345/14
www.douyin.com/collection/7099812611583117345/15
www.douyin.com/collection/7099812611583117345/16
www.douyin.com/collection/7099812611583117345/17
www.douyin.com/collection/7099812611583117345/18
www.douyin.com/collection/7099812611583117345/19
www.douyin.com/collection/7099812611583117345/20
www.douyin.com/collection/7099812611583117345/21
www.douyin.com/collection/7099812611583117345/22
www.douyin.com/collection/7099812611583117345/23
www.douyin.com/collection/7099812611583117345/24
www.douyin.com/collection/7099812611583117345/25
www.douyin.com/collection/7099812611583117345/26
www.douyin.com/collection/7099812611583117345/27
www.douyin.com/collection/7099812611583117345/28
www.douyin.com/collection/7099812611583117345/29
www.douyin.com/collection/7099812611583117345/30
www.douyin.com/collection/7099812611583117345/31

can you add the feature to download in the form below and in turn order

**Comment by Tairraos** [comment]
There are 2 answers I need to know. 
- How do you get the first URL? https://www.douyin.com/video/7099786108078230816
- How do you know this is a episodes not just a video?

If normal user is not able to get this URL, I will not implement a feature only for you only person.

Another info, if you visit one of the URs, it will redirect to real URL(https://www.douyin.com/video/7099786108078230816), just copy/paste this URL to TikTok downloader, it will work.

**Comment by Tairraos** [comment]
If you can read Chinese, you'd better to leave Chinese message to avoid to miss understanding each other.

**Comment by Dragon-97** [comment]
- I get the first episode by going to the channel and clicking on the playlist -https://drive.google.com/file/d/1LsiTuCXNalp36q9WwxuOQnIkNVX7jeA1/view?usp=sharing
- I usually go to the channel and see if they have a playlist to download in a list
- the above link I mentioned. I got it by right clicking on the number and it came out  https://drive.google.com/file/d/1qUUCFSxJYwV3-r7ZLo4x4OfAODwIaT3_/view?usp=sharing

I think there are a lot of people who need that software just like me. I hope you consider it to help me. Thanks you

**Comment by Dragon-97** [comment]
https://www.douyin.com/video/7099786108078230816
https://www.douyin.com/video/7100019194112036132
https://www.douyin.com/video/7100138978950630692
https://www.douyin.com/video/7101836179598806279
https://www.douyin.com/video/7101655376474508557
https://www.douyin.com/video/7101888366592920839
https://www.douyin.com/video/7101991701862010148
https://www.douyin.com/video/7104425717152107784
https://www.douyin.com/video/7104485847533227300
https://www.douyin.com/video/7104566621917695235
https://www.douyin.com/video/7104606060505304333
https://www.douyin.com/video/7107022855220497678
https://www.douyin.com/video/7107068511708581128
https://www.douyin.com/video/7107106482956586247
https://www.douyin.com/video/7107108676116172071
https://www.douyin.com/video/7109605713273572611
https://www.douyin.com/video/7109687583986257183
https://www.douyin.com/video/7110006419176312094
https://www.douyin.com/video/7110065296555117838
https://www.douyin.com/video/7112225810248912135
https://www.douyin.com/video/7112285702800379175
https://www.douyin.com/video/7112358848861605132
https://www.douyin.com/video/7112412873170734366
https://www.douyin.com/video/7112615387430145294
https://www.douyin.com/video/7114872614815812895
https://www.douyin.com/video/7114889688996957447
https://www.douyin.com/video/7114969546586344737
https://www.douyin.com/video/7115015226365447435
https://www.douyin.com/video/7117554146353466638
https://www.douyin.com/video/7117570162290674957
https://www.douyin.com/video/7117633128096681223

I have a normal link  like this, is there a way to enter it once, not 31 times?

**Comment by Tairraos** [comment]
For how to get playlists, I don't think this is a common feature.
For downloading from a list of video URLs, I will adding this feature in the next release. It's easy to implement, but I'm very busy at this period.

**Comment by Dragon-97** [comment]
- for downloading playlists I have searched and many people need and have not found the right one. (I hope you can develop it)
- I am having 1 software that can be loaded by list but error. Can you help me check. That software before I ordered it separately used normally until now there is an error (you can email me. I will send it to you so you can check it for me)
- I'm looking forward to your next update

**Comment by Tairraos** [comment]
I will maintain a list of features in the readme, and should implement it when I have free time. Thank you for using the app and suggesting this feature.

**Comment by Dragon-97** [comment]
thank you very much

**Comment by Tairraos** [comment]
There is a pre-release build, allow you paste [this](https://github.com/Tairraos/TikDown/issues/6#issuecomment-1180615947) once for add bunch of videos.

**Comment by Tairraos** [comment]
Issue be resolved, will include enchancement in next release.

**Comment by Dragon-97** [comment]
when you add the function to load the list. Can you allow the naming to be in top-down order? To avoid confusion. I want it to be placed in the order of the link number when pasted

**Comment by Tairraos** [comment]
It has done so before you ask.

**Comment by Dragon-97** [comment]
I want to remove all the names in front of it and replace it with only the ordinal number. Can you add that option. Thank you

**Comment by Tairraos** [comment]
I don't understand what's your point.

**Comment by viking1304** [comment]
> I don't understand what's your point.

I do. He asks for an option to have those saved as:

1.mp4
2.mp4
3.mp4
4.mp4
...

But that is not a good idea, since if you download one list like this, and then want to download another one, you will have duplicates.

Better use some multi-rename tool after download.

**Comment by Tairraos** [comment]
I will do it. Allow user to select filename template before downloading.
