### ISSUE TITLE
多个链接下载问题

### ISSUE THREAD

**Issue by tiktok666** [Tairraos/TikDown#8]
多个链接的情况下,显示下载完毕,但是保存文件夹里面只有一个视频.好像前面下载的视频会被后面下载的视频覆盖掉
版本:Tikdown-Portable-1.1.1.exe

**Comment by Tairraos** [comment]
这些视频的title是同一个。现在文件名是按title来取的。我做下检测，如果存在同名就在后面添个数字。
谢谢报告bug

**Comment by Tairraos** [comment]
在release页面有一个预发布的1.2版本，支持tiktok的新url格式。并且文件名内添加了上传日期。如果你下载的视频不是up主同一天上传的，那它们就会不一样。你可以先用它。我忽略了上传的时分秒，同一天上传的视频如果title一样还是会有同样的问题。
下一个版本可以自由配置保存的文件名，但是要添加一个配置页面，有新UI要设计，会稍微久一些才Release。

**Comment by Tairraos** [comment]
在这个提交里做了文件递归检测。下一个Release版本将会包含此代码。谢谢
